"""Data details

Revision ID: bc3f07480e98
Revises: 
Create Date: 2025-08-23 14:40:16.784525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3f07480e98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('document_id')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'documents', ['document_id'], ['id'])

    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('case_id', sa.INTEGER(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('dropbox_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_synced_to_dropbox', sa.BOOLEAN(), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=200), nullable=True),
    sa.Column('uploaded_by_id', sa.INTEGER(), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.Column('last_modified', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('person_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
